### PR TITLE
data connection from page 2 to page 3

### PR DESCRIPTION
**Pull request by amj100**
yee yee

### CODE REVIEW

**Comment by bliechty** [comment]
Penelopi is getting the data in component 2 and checking if it is an empty array.

**Comment by bliechty** [comment]
So it will only go to page 3 if there is data returned

**Comment by bliechty** [comment]
Sorry if there was any miscommunication

**Comment by amj100** [comment]
yeah i connected it so that when there is data returned then page 3 can finally use the data. i removed the dummy data in this PR and replaced the data with penelope's update

**Pull request merged**
